#!/usr/bin/env python3
"""
CivicFix - Setup Script
=======================
Automated setup script for CivicFix installation.
"""
import os
import sys
import subprocess
import secrets
from pathlib import Path

def print_step(step, message):
    """Print a setup step."""
    print(f"\n[{step}] {message}")

def run_command(command, check=True):
    """Run a shell command."""
    try:
        result = subprocess.run(
            command,
            shell=True,
            check=check,
            capture_output=True,
            text=True
        )
        return result.returncode == 0, result.stdout, result.stderr
    except subprocess.CalledProcessError as e:
        return False, e.stdout, e.stderr

def check_python_version():
    """Check if Python version is 3.8 or higher."""
    print_step("1/8", "Checking Python version...")
    
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print(f"❌ Python 3.8+ required. Found: {version.major}.{version.minor}")
        return False
    
    print(f"✓ Python {version.major}.{version.minor}.{version.micro} detected")
    return True

def create_virtual_environment():
    """Create virtual environment."""
    print_step("2/8", "Creating virtual environment...")
    
    venv_path = Path("venv")
    if venv_path.exists():
        print("✓ Virtual environment already exists")
        return True
    
    try:
        import venv
        venv.create("venv", with_pip=True)
        print("✓ Virtual environment created")
        return True
    except Exception as e:
        print(f"❌ Failed to create virtual environment: {e}")
        return False

def install_dependencies():
    """Install required packages."""
    print_step("3/8", "Installing dependencies...")
    
    # Determine pip path
    if os.name == 'nt':  # Windows
        pip_path = "venv\\Scripts\\pip"
    else:
        pip_path = "venv/bin/pip"
    
    success, stdout, stderr = run_command(f"{pip_path} install -r backend/requirements.txt")
    
    if success:
        print("✓ Dependencies installed successfully")
        return True
    else:
        print(f"❌ Failed to install dependencies: {stderr}")
        return False

def create_environment_file():
    """Create .env file if it doesn't exist."""
    print_step("4/8", "Setting up environment configuration...")
    
    env_path = Path(".env")
    if env_path.exists():
        print("✓ .env file already exists")
        return True
    
    # Generate secure keys
    secret_key = secrets.token_hex(32)
    jwt_secret_key = secrets.token_hex(32)
    
    env_content = f"""# CivicFix Environment Configuration
# ==================================
# Generated by setup script

FLASK_ENV=development
SECRET_KEY={secret_key}
JWT_SECRET_KEY={jwt_secret_key}
MONGO_URI=mongodb://localhost:27017/civicfix
HOST=0.0.0.0
PORT=5000
DEBUG=True
"""
    
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        print("✓ .env file created with secure keys")
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False

def create_upload_directories():
    """Create upload directories."""
    print_step("5/8", "Creating upload directories...")
    
    try:
        Path("uploads/complaints").mkdir(parents=True, exist_ok=True)
        Path("uploads/resolutions").mkdir(parents=True, exist_ok=True)
        print("✓ Upload directories created")
        return True
    except Exception as e:
        print(f"❌ Failed to create upload directories: {e}")
        return False

def check_mongodb():
    """Check if MongoDB is installed and running."""
    print_step("6/8", "Checking MongoDB...")
    
    try:
        from pymongo import MongoClient
        client = MongoClient("mongodb://localhost:27017/", serverSelectionTimeoutMS=2000)
        client.server_info()
        print("✓ MongoDB is running")
        return True
    except Exception:
        print("⚠ MongoDB is not running or not installed")
        print("\n  To install MongoDB:")
        print("  - Windows: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/")
        print("  - Linux: sudo apt-get install mongodb")
        print("  - macOS: brew install mongodb-community")
        print("\n  To start MongoDB:")
        print("  - Windows: net start MongoDB")
        print("  - Linux: sudo systemctl start mongod")
        print("  - macOS: brew services start mongodb-community")
        return False

def create_admin_account():
    """Prompt to create admin account."""
    print_step("7/8", "Admin Account Setup")
    
    response = input("\nDo you want to create an admin account now? (y/N): ")
    if response.lower() != 'y':
        print("⏭ Skipping admin account creation")
        print("  You can create an admin account later using the API")
        return True
    
    print("\nAdmin Certification ID format: CIVICFIX-ADMIN-XXXXXX")
    print("Contact your municipal authority for the certification ID\n")
    
    return True

def print_completion_message():
    """Print completion message with next steps."""
    print_step("8/8", "Setup Complete!")
    
    print("""
╔══════════════════════════════════════════════════════════════╗
║                    Setup Complete!                           ║
╚══════════════════════════════════════════════════════════════╝

Next Steps:
-----------

1. Activate the virtual environment:
   
   Windows:
   venv\\Scripts\\activate
   
   Linux/macOS:
   source venv/bin/activate

2. Start MongoDB (if not already running):
   
   Windows: net start MongoDB
   Linux:   sudo systemctl start mongod
   macOS:   brew services start mongodb-community

3. Run the application:
   
   python run.py

4. Open your browser and navigate to:
   
   http://localhost:5000

Default Access:
---------------
- Citizen Registration: Available on the homepage
- Admin Registration: Use certification ID format "CIVICFIX-ADMIN-XXXXXX"

Configuration:
--------------
- Edit .env file to customize settings
- Update emergency zone coordinates in backend/config.py

Support:
--------
- Documentation: README.md
- Issues: https://github.com/your-org/civicfix/issues

Thank you for using CivicFix!
""")

def main():
    """Main setup function."""
    print("""
╔══════════════════════════════════════════════════════════════╗
║              CivicFix - Setup Script                         ║
║         Smart Public Issue Reporting Platform                ║
╚══════════════════════════════════════════════════════════════╝
""")
    
    steps = [
        ("Python Version", check_python_version),
        ("Virtual Environment", create_virtual_environment),
        ("Dependencies", install_dependencies),
        ("Environment File", create_environment_file),
        ("Upload Directories", create_upload_directories),
        ("MongoDB Check", check_mongodb),
        ("Admin Account", create_admin_account),
    ]
    
    for name, func in steps:
        if not func():
            print(f"\n❌ Setup failed at step: {name}")
            sys.exit(1)
    
    print_completion_message()

if __name__ == '__main__':
    main()
